openapi: 3.0.3
info:
  title: Simple MEC Discovery API
  version: 0.8.1
  description: |
    # Find your nearest MEC platform
    ---
    Network operators will typically have multiple MEC sites in a given territory. Connecting your application to a server on the closest MEC platform means the lowest latency - however, the physical location of a user is not an accurate match to the closest MEC site, due to the way operator networks are configured. This API returns the MEC platforms with the _shortest network path_ to the client making the request, and hence the lowest propagation delay.
    * If you have a server instance deployed there, connect to it to gain the lowest latency
    * Or if not, you may wish to deploy an instance there using the APIs of the cloud provider supporting that zone.
    
      This API is intended to be called by a client application hosted on a UE attached to the operator network. _Note that the API parameters have been listed in this 'simple API' to align with the full API, but are optional and may not be supported by the API server_
    ---
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
externalDocs:
  description: Product documentation at CAMARA
  url: https://github.com/camaraproject/

servers:
  # Added by API Auto Mocking Plugin
  - url: '{apiRoot}/{basePath}'
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
      basePath:
        default: /mecplatforms/v0
        description: Base path for the get MEC platform API
security:
  - oAuth2ClientCredentials: []

tags:
  - name: Discovery
    description: |
       Find the closest MEC platform to the UE (user equipment)

paths:
  /:
    get:
      responses:
        '200':
          description: Bookmark
          content:
            application/json:
              schema:
                title: getResourcesResponse
                type: object
                properties:
                  resources:
                    type: array
                    items: 
                      $ref: '#/components/schemas/Resources'
                  links:
                    type: array
                    items:
                      oneOf:
                        - $ref: '#/components/schemas/LinksCommon'
        '401':
          $ref: '#/components/responses/Unauthorized'
        default:
          $ref: '#/components/responses/Unexpected'
      security:
        - oAuth2ClientCredentials: []
        - three_legged:
          - "mec-platform-read"

      tags:
        - Discovery
      operationId: bookmark
      summary: API bookmark
      description: API bookmark

  /mecplatforms:
    get:
      operationId: get-mecplatforms
      parameters:
        - $ref: '#/components/parameters/region'
        - $ref: '#/components/parameters/zone'        
        - $ref: '#/components/parameters/serviceProfileId'
        - $ref: '#/components/parameters/subscriberDensity'
        - $ref: '#/components/parameters/UEIdentityType'
        - $ref: '#/components/parameters/UEIdentity'
      responses:
        '200':
          description: MEC platforms matching query parameters
          content:
            application/json:
              schema:
                title: GetMECPlatformsResponse
                type: object
                properties:
                  MECPlatforms:
                    type: array
                    items:
                      $ref: '#/components/schemas/ResourcesMecPlatform'
                  links:
                    type: array
                    items:
                      oneOf:
                        - $ref: '#/components/schemas/LinksAllMecPlatforms'
                        - $ref: '#/components/schemas/LinksCommon'
        '401':
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: "#/components/responses/Generic403"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        default:
          $ref: '#/components/responses/Unexpected'
      tags:
        - Discovery
      summary: Returns the name of the closest MEC platform(s) to the UE that sent the request.
      description: ON receiving this request, the network will calculate which of its MEC platforms have the shortest network path to the UE (terminal) from which the request was made. 
   
components:
  securitySchemes:
    oAuth2ClientCredentials:
      description: |
        The Get MEC Platform API makes use of the OAUTH 2.0 client credentials grant which is applicable for server to server use cases involving trusted partners or clients without any protected user data involved. In this method the API invoker client is registered as a confidential client with an authorization grant type of client_credentials
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: "{tokenUrl}"
          scopes: {}  
    three_legged:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/authorize
          tokenUrl: https://auth.example.com/token
          scopes:
            mecplatforms-read: Retrieve list of MEC Platforms

  schemas:
    Resources:
      type: array
      items:
        oneOf:
          - $ref: '#/components/schemas/LinksAllMecPlatforms' 
      additionalProperties: false
    ResourcesMecPlatform:
      type: object
      properties:
        ern:
          $ref: '#/components/schemas/TypesEdgeResource'
        zone:
          $ref: '#/components/schemas/TypesZoneId'
        region:
          $ref: '#/components/schemas/TypesRegionId'
        status:
          description: Status of the MEC Platform (default is 'unknown')
          type: string
          enum:
            - active
            - inactive
            - unknown
          default: unknown
        properties:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              data:
                type: object
      additionalProperties: false

    TypesEdgeResource:
      description: |
        An object defined by the service provider representing an edge resource within its network domain, such as a MEC Platform.  The string contains colon-separated metadata in the form   ern:<tsp-identifier>:<tsp-region>:<resource-type>:<resource-identifier>:<tsp-extensions>
      type: string
      additionalProperties: false     
    TypesZoneId:
      description: |
        Unique identifier representing a zone
      type: string
      additionalProperties: false  
    TypesRegionId:
      description: |
        Unique identifier representing a region
      type: string
      additionalProperties: false
    TypesSuccess:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        links:
          $ref: '#/components/schemas/LinksCommon'
      required:
        - code
        - message
        - links
      additionalProperties: false
    TypesError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        links:
          $ref: '#/components/schemas/LinksCommon'
      required:
        - code
        - message
        - links
      additionalProperties: false
    TypesUEIdentityType:
      description: Type of User Equipment identifier used in `UEIdentity`.
      type: string
      enum:
        - IPAddress
        - MSISDN
        - IMEI
        - MDN
        - GPSI
    TypesUEIdentity:
      description: Identifier value for User Equipment. The type of identifier is defined by the 'UEIdentityType' parameter.
      type: string
    ErrorInfo:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status code returned along with this error response
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
      required:
        - status
        - code
        - message

###########################################
# LINKS
###########################################
    LinksAllMecPlatforms:
      type: object
      readOnly: true
      properties:
        link:
          type: object
          properties:
            rel:
              type: string
              pattern: ListMECPlatforms
              example: ListMECPlatforms
            method:
              type: string
              pattern: get
              example: get
            href:
              type: string
              pattern: '\/mecplatforms'
              example: /mecplatforms
          required:
            - href
            - rel
            - method
      additionalProperties: false 

    LinksSelf:
      type: object
      readOnly: true
      properties:
        link:
          type: object
          properties:
            rel:
              type: string
              pattern: self
              example: self
            method:
              type: string
              pattern: get
              example: get
            href:
              type: string
              format: uri
          required:
            - href
            - rel
            - method
      additionalProperties: false
    LinksVersionHistory:
      type: object
      readOnly: true
      properties:
        link:
          type: object
          properties:
            rel:
              type: string
              pattern: version-history
              example: version-history
            method:
              type: string
              pattern: get
              example: get
            href:
              type: string
              format: uri
          required:
            - href
            - rel
            - method
      additionalProperties: false
    LinksTermsOfService:
      type: object
      readOnly: true
      properties:
        link:
          type: object
          properties:
            rel:
              type: string
              pattern: terms-of-service
              example: terms-of-service
            method:
              type: string
              pattern: get
              example: get
            href:
              type: string
              format: uri
          required:
            - href
            - rel
            - method
      additionalProperties: false
    LinksBookmark:
      type: object
      readOnly: true
      properties:
        link:
          type: object
          properties:
            rel:
              type: string
              pattern: bookmark
              example: bookmark
            method:
              type: string
              pattern: get
              example: get
            href:
              type: string
              format: uri
          required:
            - href
            - rel
            - method
      additionalProperties: false
    LinksCommon:
      type: array
      readOnly: true
      items:
        oneOf:
          - $ref: '#/components/schemas/LinksSelf'
          - $ref: '#/components/schemas/LinksVersionHistory'
          - $ref: '#/components/schemas/LinksTermsOfService'
          - $ref: '#/components/schemas/LinksBookmark'

################################
# PARAMETERS
################################
            
  parameters:
    region:
      name: region
      description: MEC region ID
      in: query
      required: false
      schema:
        type: string
    zone:
      name: zone
      description: MEC zone ID
      in: query
      required: false
      schema:
        type: string  
    serviceProfileId:
      name: serviceProfileId
      description: service profile identifier
      in: query
      required: false
      schema:
        type: string
    subscriberDensity:
      name: subscriberDensity
      description: Minimum number of 4G/5G subscribers per square kilometer.
      in: query
      required: false
      schema:
        type: integer
    UEIdentityType:
      name: ueIdentityType
      description: Type of User Equipment identifier used in `UEIdentity`.
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/TypesUEIdentityType'
    UEIdentity:
      name: ueIdentity
      description: Identifier value for User Equipment. The type of identifier is defined by the UEIdentityType parameter.
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/TypesUEIdentity'
###################################
# RESPONSES
####################################
  responses:
    OK:
      description: HTTP 200 OK
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TypesSuccess'  
    Unauthorized:
      description: HTTP 401 Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TypesError'
    NotFound:
      description: HTTP 404 The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TypesError'            
    Unexpected:
      description: HTTP 500 Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/TypesError'
    Generic403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 403
            code: PERMISSION_DENIED
            message: "Operation not allowed: ..."
    Generic500:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 500
            code: INTERNAL
            message: "Internal server error: ..."
    Generic503:
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 503
            code: UNAVAILABLE
            message: "Service unavailable"

 
